# Generated by Django 3.1.1 on 2020-12-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='update',
            new_name='Last_Modified',
        ),
    ]
